# MySQL configuration for Spree server.
# Install MySQL: bash deploy/install_mysql.sh

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: spree
  password: spree123
  host: 127.0.0.1

development:
  <<: *default
  database: spree_development

test:
  <<: *default
  database: spree_test

production:
  primary: &primary_production
    <<: *default
    database: spree_production
  cache:
    <<: *primary_production
    database: spree_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: spree_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: spree_production_cable
    migrations_paths: db/cable_migrate
